### ISSUE TITLE
Task 01 Connect to API

### ISSUE THREAD

**Issue by Arda-Dinc04** [Arda-Dinc04/Market-Insight-Algorithms#1]
- PRIORITY #1: Connect to API https://www.nasdaq.com/nasdaq-data-link

- Create a table/dataframe using python pulling data from Apple, Google, Etc 10ish companies.

- Pull current "price, volume, etc data" from API for the Ticker/Intrustment column from Robinhood_Profit.csv and display in a new dataframe

**Comment by lljw9999** [comment]
wanna get high

**Comment by Arda-Dinc04** [comment]
Move code py code to ipynb and attempt to extract the data in the table to a folder of a csv file.
- Details further down the line will import matplotlib.pyplot, seaborn, numpy

**Comment by tonykorycki** [comment]
did it but lowkey could not find data for most on any main bases

**Comment by Arda-Dinc04** [comment]
Ok thats alr, gonna keep trying to find a way to pull data not from the web but a data provider with an api

**Comment by tonykorycki** [comment]
no thats what i did but for these tickers my code would give a lot of 404s when looking for WIKIs and when I excluded those the table was like 10 entries long

**Comment by Arda-Dinc04** [comment]
interesting okk well def push the code to a test folder with you name and add issues to that folder, I wanna take a look at that see if its possible to debug
